### ISSUE TITLE
MooseX::Singleton reports that the instance was already created.

### ISSUE THREAD

**Issue by localh0rst** [localh0rst/OpenSearch-Perl#12]
I also had a situation where the singleton of `OpenSearch::Base` could not be created. MooseX::Singleton reported 
that the instance was already created. I tried to replace it by (example):

```
package OpenSearch::Base;

my $instance;

sub set_instance ($class, $self) {
   $instance = $self;
}
sub instance ($class) {
  $instance;
}

1;
```

```
package OpenSearch;

...

sub BUILD {
  ..
  OpenSearch::Base->set_instance($self->base);
}
```

and then it started working again. Not sure how to replicate the problem

_Originally posted by @nicolasfranck in https://github.com/localh0rst/OpenSearch-Perl/issues/7#issuecomment-2188186746_

**Comment by localh0rst** [comment]
The only way i could reproduce this was by manually creating a `OpenSearch::Base` instance and running `OpenSearch::Base->initialize` afterwards:

```
my $base = OpenSearch::Base->new(...);
my $d = OpenSearch::Base->initialize;
```

However this should not happen. `->initialize` is only used in the `default` builder method (tbh, the default is pointless there).  But since this attribute is `lazy` it should never be called. This cannot happen in any other Class calling `->instance`. This would fail because of missing arguments to `new`.

Did you, by any means, create the Singleton by yourself? I`d try to fix that by removing

```
lazy => 1,
default => sub { OpenSearch::Base->initialize; }
```

from OpenSearch.pm. This way there is only one way a new singleton instance is created (in `sub BUILD`).

**Comment by nicolasfranck** [comment]
And what if you create two instances of OpenSearch (each one for a different opensearch server)? The BUILD is called twice, so therefore the OpenSearch::Base twice created. MooseX::Singleton probably has a check on how many times the "new" method is called.

Besides, a singleton that depends on variadic input from the OpenSearch package is not really a singleton, not?

I'll have a look

**Comment by localh0rst** [comment]
Hmmm, i guess you're right with both. `set_instance` is probably not needed. This can be done in `BUILD`since its run after object creation:

```
package OpenSearch::Base;

my $instance;

sub BUILD($self) {
  $instance = $self;
}

sub instance ($class) {
  $instance;
}

1;
```

At least in my tests both instances (for different servers) where created successful and tests were okay. Its currently in the development branch

**Comment by nicolasfranck** [comment]
but, in the example from https://github.com/localh0rst/OpenSearch-Perl/commit/f8047630b58da132264e52eda98c52585e69d46f, the variable `$instance`, which is located
on the package level is overwritten each time a new OpenSearch::Base object is created.
So your first opensearch object will accidentally speak to the server that was meant for the second opensearch object.
So that MooseX::Singleton was actually complaining rightfully as it detected a problem.

I am was preparing a PR that passes the base object to where it is needed.
And I renamed it to OpenSearch::Client to make its function more clear. Is that ok?

**Comment by localh0rst** [comment]
Maybe im wrong. But if it gets overwritten, my tests would not work:
```
my $os1 = OpenSearch->new(hosts => ['localhost:9200'], ...);
my $os2 = OpenSearch->new(hosts => ['localhost:9999'], ...);
print Dumper $os1->base->hosts;
print Dumper $os2->base->hosts;
print Dumper $os1->base->hosts;
```
This correctly reports:

```
$VAR1 = [
          'localhost:9200'
        ];
$VAR1 = [
          'localhost:9999'
        ];
$VAR1 = [
          'localhost:9200'
        ];
```

Shouldn't that report `localhost:9999`for the third `Dumper`if youre correct?

Im Okay with any PR (help is very much appreciated). I was also thinking about passing the object around in all classes that require it.

**Comment by nicolasfranck** [comment]
Weird, I was expecting the lexical variable outside of a block to behave like an `our` variable. How can something like`sub instance { $instance; }` know what variable to return?

**Comment by localh0rst** [comment]
Sorry for the confusion. It does not work. Youre right. My test was wrong. I checked the base class instead of the instance which is used by all other Submodules:
```
my $os1 = OpenSearch->new(hosts => ['localhost:9200'], ...);
my $os2 = OpenSearch->new(hosts => ['localhost:9999'], ...);
print Dumper $os1->base->instance->hosts;
print Dumper $os2->base->instance->hosts;
print Dumper $os1->base->instance->hosts;
```
reports:
```
$VAR1 = [
          'localhost:9999'
        ];
$VAR1 = [
          'localhost:9999'
        ];
$VAR1 = [
          'localhost:9999'
        ];
```

**Comment by nicolasfranck** [comment]
I'll send you the PR somewhere in the evening

**Comment by localh0rst** [comment]
Fixes by https://github.com/localh0rst/OpenSearch-Perl/pull/14

Thanks for the PR
