### ISSUE TITLE
Handling of connection errors are not thrown but returned as return value from api call

### ISSUE THREAD

**Issue by nicolasfranck** [localh0rst/OpenSearch-Perl#19]
Due to line https://github.com/localh0rst/OpenSearch-Perl/blob/main/lib/OpenSearch/Base.pm#L88
all connection errors are caught and returned as the return value of the api call.

This means that next to `Mojo::Response`, an api call can also return a string, containing an connection error,
which is unexpected.

Is it necessary to catch connection errors? Without it, connection errors are thrown, and then it is up to the client
code to catch this.

**Comment by localh0rst** [comment]
Maybe it would make sense to also return an `OpenSearch::Response`on Connection errors?
So non async clients can catch errors via:

```
if($response->success) {
  ...
} else {
  say $response->error;
}
```

Async clients could catch the error like:

```
$response->catch(sub($res) {
  say $res->error;
});
```

This would only require small changes to `OpenSearch::Response` and the `response`method of `OpenSearch::Base`.
What do you think about that?

**Comment by nicolasfranck** [comment]
That's fine too

**Comment by localh0rst** [comment]
I pushed the first version of that in the connection_error_handling branch.
Would you mind testing this? After your testing i will merge this with main and close the issue

**Comment by localh0rst** [comment]
OpenSearch::Response is now also returned on Connection errors. Merged with main

**Comment by nicolasfranck** [comment]
ah sorry, forgot about this ;-)
