### ISSUE TITLE
Disable warnings for experimental features

### ISSUE THREAD

**Issue by nicolasfranck** [localh0rst/OpenSearch-Perl#3]
Your module is using experimental features like `signatures` that generates a lot of warning messages.

I believe you can disable those messages by putting `no warnings qw(experimental::signatures);` after
`use feature qw(signatures)`.

**Comment by nicolasfranck** [comment]
I know that more recent perl versions do not mark this feature as experimental anymore, but a lot of installations tend to use older versions.

**Comment by localh0rst** [comment]
> I know that more recent perl versions do not mark this feature as experimental anymore, but a lot of installations tend to use older versions.

Yes. I m using 5.38 so this was not an issue. However. That should be fixxed on GitHub no. CPAN Module, as mentioned in the other Issue, will be releases later this week. 

Thanks for reporting these issues

**Comment by nicolasfranck** [comment]
Can I reopen this issue?

Apparently the use of statement `use Moose` and its relatives, disables the perl `v5.20` features.

```
package T;

use strict;
use warnings;
use feature qw(signatures);
no warnings qw(experimental::signatures);
use Moose;

sub f () {
    print "f";
}

1;
```

```
$ perl -c T.pm 
The signatures feature is experimental at T.pm line 9.
T.pm syntax OK
```

vs.

```
package T;

use strict;
use warnings;
use feature qw(signatures);
no warnings qw(experimental::signatures);

sub f () {
    print "f";
}

1;
```

which succeeds (but not what you probably want)

and now with Moose before it:

```
package T;

use strict;
use warnings;
use Moose;
use feature qw(signatures);
no warnings qw(experimental::signatures);

sub f () {
    print "f";
}

1;
```

I tested it with the library `Moo` which has the same problem by the way.

So best to put these two lines always at the end. Features always have a lexical effect.

https://perldoc.perl.org/feature#Lexical-effect

**Comment by nicolasfranck** [comment]
I'll create a PR if you want

**Comment by localh0rst** [comment]
Thanks for the PR. Will be releasing this to CPAN this weekend.
