### ISSUE TITLE
$index->exists should not try to decode JSON when using a HEAD request

### ISSUE THREAD

**Issue by nicolasfranck** [localh0rst/OpenSearch-Perl#4]
The method [OpenSearch::Index::Exists::execute](https://github.com/localh0rst/OpenSearch-Perl/blob/main/lib/OpenSearch/Index/Exists.pm#L18) uses a http `HEAD` request to test if
an index exists (which is fine), but then tries to decode an use the attribute `error`, leading to a string
response like this:

```
Can't use an undefined value as a HASH reference at $HOME/.plenv/versions/5.22.1/lib/perl5/site_perl/5.22.1/OpenSearch/Response.pm
```

**Comment by localh0rst** [comment]
Issue is now fixed on Gihub. CPAN Release will follow later this week after more tests are written

**Comment by nicolasfranck** [comment]
Thanks for the quick response!
