### ISSUE TITLE
Search parameter track_total_hits should also support boolean values

### ISSUE THREAD

**Issue by nicolasfranck** [localh0rst/OpenSearch-Perl#8]
The current parameter validation on the search parameter `track_total_hits` is set to be an integer.

But according to the documentation the value can also be a boolean value, being either a real JSON boolean  (e.g. `true`)
or a stringified boolean (e.g. `"true"`). 

cf. https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-your-data.html#track-total-hits

Apparently this parameter is set by default to `10000` (by opensearch I guess), so for any total above
that you'll have to set this value very high (e.g. `10000000`), or have a means to set it to `true`.

Given the fact that `Bool` in Moose can be `0` or `1`, a validation like `Bool|Int` would not make any sense.
Set it to `Str`? In perl everything is a string (even if you supply an integer).

**Comment by localh0rst** [comment]
Changed it to Str. Until There is a better way to handle parameters
