### ISSUE TITLE
Attribute OpenSearch::Response#error should be regular hash?

### ISSUE THREAD

**Issue by nicolasfranck** [localh0rst/OpenSearch-Perl#9]
The attribute [OpenSearch::Response#error](https://github.com/localh0rst/OpenSearch-Perl/blob/main/lib/OpenSearch/Response.pm#L24) is set to a `Hash::AsObject` instead of the
regular hash as returned by ElasticSearch. 

Pros:

* makes it easier to read like `$res->error->caused_by->reason`

Cons:
* the return value is a bit unexpected
* sometimes hard to work with (e.g. how to access `error.root_cause.0.reason`?).
* any JSON encoder has to be configured to allow blessed references, if you want to stringify it.
* the module is quite old.
* `$res->data->{error}` is also blessed as `Hash::AsObject` (because supplied to Hash::AsObject as a reference) so there is no way to use the error object via that way
* Not every `error` is actually a hash. e.g. try http://localhost:9200/_aliases?index=rubish&name=rubish

**Comment by localh0rst** [comment]
Hmmm, yeah. I agree that its an unexpected return value compared to the rest of the response object (which is a normal hash). I think you're right and i should set it to:
`$self->error( $self->data->{error} );`

That is what you had in mind, correct?
